title: 位毛的博客
email: wallyvay@gmail.com
description: >-
  位毛的播客，since 2011
baseurl: "/blog" # 设置为仓库名
url: "https://wallyvay.github.io" # 替换为您的GitHub用户名
twitter_username: wallyvay
github_username:  wallyvay

# 构建设置
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 博客设置
permalink: /:year/:month/:day/:title/

# 页面结构
collections:
  macintosh:
    output: true
    permalink: /:collection/:name/
  疯言疯语:
    output: true
    permalink: /:collection/:name/
  讲点正事儿:
    output: true
    permalink: /:collection/:name/
  日本之旅:
    output: true
    permalink: /:collection/:name/
  两人一狗去拉萨:
    output: true
    permalink: /:collection/:name/
  日記:
    output: true
    permalink: /:collection/:name/
  photography:
    output: true
    permalink: /:collection/:name/

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - migrate_blog.rb
  - weimao.me/ 